#include "input.h"

static_assert(NUM_INPUTS == 14);

// key none
#define knone SDL_SCANCODE_UNKNOWN

// button none
#define bnone SDL_CONTROLLER_BUTTON_INVALID

InputBinding g_InputBindings[NUM_INPUTS] = {
	/* INPUT_MOVE_RIGHT    */ { SDL_SCANCODE_RIGHT, knone, SDL_CONTROLLER_BUTTON_DPAD_RIGHT, bnone },
	/* INPUT_MOVE_UP       */ { SDL_SCANCODE_UP,    knone, SDL_CONTROLLER_BUTTON_DPAD_UP,    bnone },
	/* INPUT_MOVE_LEFT     */ { SDL_SCANCODE_LEFT,  knone, SDL_CONTROLLER_BUTTON_DPAD_LEFT,  bnone },
	/* INPUT_MOVE_DOWN     */ { SDL_SCANCODE_DOWN,  knone, SDL_CONTROLLER_BUTTON_DPAD_DOWN,  bnone },

	/* INPUT_A             */ { SDL_SCANCODE_Z, knone, SDL_CONTROLLER_BUTTON_A, bnone },
	/* INPUT_B             */ { SDL_SCANCODE_X, knone, SDL_CONTROLLER_BUTTON_B, bnone },

	/* INPUT_PAUSE         */ { SDL_SCANCODE_ESCAPE, knone, SDL_CONTROLLER_BUTTON_START, bnone },

	/* INPUT_UI_RIGHT      */ { SDL_SCANCODE_RIGHT, knone, SDL_CONTROLLER_BUTTON_DPAD_RIGHT, bnone },
	/* INPUT_UI_UP         */ { SDL_SCANCODE_UP,    knone, SDL_CONTROLLER_BUTTON_DPAD_UP,    bnone },
	/* INPUT_UI_LEFT       */ { SDL_SCANCODE_LEFT,  knone, SDL_CONTROLLER_BUTTON_DPAD_LEFT,  bnone },
	/* INPUT_UI_DOWN       */ { SDL_SCANCODE_DOWN,  knone, SDL_CONTROLLER_BUTTON_DPAD_DOWN,  bnone },

	/* INPUT_UI_CONFIRM    */ { SDL_SCANCODE_Z, SDL_SCANCODE_RETURN, SDL_CONTROLLER_BUTTON_A, SDL_CONTROLLER_BUTTON_START },
	/* INPUT_UI_CANCEL     */ { SDL_SCANCODE_X, SDL_SCANCODE_ESCAPE, SDL_CONTROLLER_BUTTON_B, bnone },

	/* INPUT_DEBUG         */ { SDL_SCANCODE_A, knone, SDL_CONTROLLER_BUTTON_X, bnone },
};
